source:      src
destination: dist
exclude:     [ "*.scss", "*.js" ]
permalink:   pretty

prose:
  siteurl: 'https://eddiema.de/'
  rooturl: 'src'
  media: 'src/images'
  ignore:
    - 'src/_layouts'
    - 'src/css'
    - 'src/js'
    - 'src/images'
    - 'src/*.html'
  metadata:
    src/_drafts:
      - name: 'category'
        field:
          element: 'text'
      - name: 'layout'
        field:
          element: 'hidden'
          value: 'post'
    src/_posts:
      - name: 'category'
        field:
          element: 'text'
      - name: 'layout'
        field:
          element: 'hidden'
          value: 'post'
